### ISSUE TITLE
Dando estilos al authapp

### ISSUE THREAD

**Issue by Blandskron** [Blandskron/PortafolioCursoOnlineDjango#16]
Investigar el diseño de la autenticacion ejemplo el login signup basandonos en aplicacion existentes ejemplo redessociales o sitios ecommerce

**Comment by AlvaroMCV** [comment]
Se estilizó pagina de login y signup basandose en el login de instagram. Se utilizó un card de bootstrap para encapsular el form tanto del login como del signup
![Captura de pantalla 2024-06-08 010620](https://github.com/Blandskron/PortafolioCursoOnlineDjango/assets/163361666/283381c8-969a-48c4-a694-515d927d88f5)
![Captura de pantalla 2024-06-08 010603](https://github.com/Blandskron/PortafolioCursoOnlineDjango/assets/163361666/0f01e940-5641-4e27-8709-f60ba16fc912)
